auto:        true
server:      true
server_port: 4000
url:         mapnik.org
lsi:         false
pygments:    true
markdown:    rdiscount
permalink:   /news/:year/:month/:day/:title

rdiscount:
  extensions: [smart]
